# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ifnone": "00_core.ipynb",
         "make_date": "00_core.ipynb",
         "add_datepart": "00_core.ipynb",
         "add_lag_features": "00_core.ipynb",
         "add_lag_percentage_gain_features": "00_core.ipynb",
         "add_moving_average_features": "00_core.ipynb",
         "add_moving_average_percentage_gain_features": "00_core.ipynb",
         "add_expanding_features": "00_core.ipynb",
         "add_trend_features": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://shanaka-desoysa.github.io/timeseries_feature_engineering/"

git_url = "https://github.com/shanaka-desoysa/timeseries_feature_engineering/tree/master/"

def custom_doc_links(name): return None
