# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["core.py"]

doc_url = "https://shanaka-desoysa.github.io/timeseries_feature_engineering/"

git_url = "https://github.com/shanaka-desoysa/timeseries_feature_engineering/tree/{branch}/"

def custom_doc_links(name): return None
